### ISSUE TITLE
Error when running on Ubuntu

### ISSUE THREAD

**Issue by joffemd** [ReasonFoundation/pension_crawler#3]
reason@pensiondata:~/pension_crawler$ scrapy crawl pensions
2018-01-30 23:01:10 [scrapy.utils.log] INFO: Scrapy 1.5.0 started (bot: pension_crawler)
2018-01-30 23:01:10 [scrapy.utils.log] INFO: Versions: lxml 4.1.1.0, libxml2 2.9.7, cssselect 1.0.3, parsel 1.3.1, w3lib 1.19.0, Twisted 17.9.0, Python 3.5.2 (default, Nov 23 2017, 16:37:01) - [GCC 5.4.0 20160609], pyOpenSSL 17.5.0 (OpenSSL 1.1.0g  2 Nov 2017), cryptography 2.1.4, Platform Linux-4.11.0-1016-azure-x86_64-with-Ubuntu-16.04-xenial
2018-01-30 23:01:10 [scrapy.crawler] INFO: Overridden settings: {'BOT_NAME': 'pension_crawler', 'SPIDER_MODULES': ['pension_crawler.spiders']}
2018-01-30 23:01:10 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.corestats.CoreStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.memusage.MemoryUsage',
 'scrapy.extensions.logstats.LogStats']
Unhandled error in Deferred:
2018-01-30 23:01:10 [twisted] CRITICAL: Unhandled error in Deferred:

2018-01-30 23:01:10 [twisted] CRITICAL:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/twisted/internet/defer.py", line 1386, in _inlineCallbacks
    result = g.send(result)
  File "/usr/local/lib/python3.5/dist-packages/scrapy/crawler.py", line 79, in crawl
    self.spider = self._create_spider(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/scrapy/crawler.py", line 102, in _create_spider
    return self.spidercls.from_crawler(self, *args, **kwargs)
  File "/home/reason/pension_crawler/pension_crawler/spiders/pensions.py", line 62, in from_crawler
    crawler.settings
  File "/home/reason/pension_crawler/pension_crawler/spiders/pensions.py", line 53, in parse_settings
    raise NotConfigured('Search engine ID not set.')
scrapy.exceptions.NotConfigured: Search engine ID not set.

**Comment by tishmen** [comment]
This is due to missing secrets file. File was sent via Upwork
